### ISSUE TITLE
데이터베이스 단어 추가/제거 [오류 창이 뜨면서 프로그램이 자동으로 종료되는 문제]

### ISSUE THREAD

**Issue by keamlfea** [hsheric0210/AutoKkutu#63]
안녕하세요
수동으로 단어 추가/제거 할 때 오류가 발생하면서 프로그램이 자동으로 종료됩니다
https://ibb.co/PTPM8Hv
확인 부탁드립니다

**Comment by keamlfea** [comment]
https://ibb.co/YpzkHjt
콘솔 로그입니다

**Comment by keamlfea** [comment]
새로운 폴더에 압축 풀어서 시도해도 수동으로 추가하면 동일한 오류가 뜨네요

**Comment by keamlfea** [comment]
CefSharp, 최신 버전입니다

**Comment by keamlfea** [comment]
Program crashed! Report this to the developer.
System.InvalidOperationException: BeginTransaction can only be called when the connection is open.
   at Microsoft.Data.Sqlite.SqliteConnection.BeginTransaction(IsolationLevel isolationLevel, Boolean deferred)
   at Microsoft.Data.Sqlite.SqliteConnection.BeginTransaction(IsolationLevel isolationLevel)
   at Microsoft.Data.Sqlite.SqliteConnection.BeginDbTransaction(IsolationLevel isolationLevel)
   at System.Data.Common.DbConnection.System.Data.IDbConnection.BeginTransaction()
   at AutoKkutuLib.Database.AbstractDatabaseConnection.BeginTransaction() in C:\projects\autokkutu\AutoKkutuLib\Database\AbstractDatabaseConnection.cs:line 50
   at AutoKkutuLib.Database.Jobs.Word.BatchWordAdditionJob.Execute(String[] wordList) in C:\projects\autokkutu\AutoKkutuLib\Database\Jobs\Word\BatchWordAdditionJob.cs:line 27
   at AutoKkutuGui.DatabaseManagement.BatchWordJob(String content, BatchJobOptions options, WordFlags flags) in C:\projects\autokkutu\AutoKkutuGui\DatabaseManagement.xaml.cs:line 36
   at AutoKkutuGui.DatabaseManagement.Batch_Submit_Click(Object sender, RoutedEventArgs e) in C:\projects\autokkutu\AutoKkutuGui\DatabaseManagement.xaml.cs:line 39
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at AutoKkutuGui.App.Main()

**Comment by keamlfea** [comment]
https://ci.appveyor.com/api/buildjobs/bmcb5he1777q0v31/artifacts/Windows.x64.ReleaseCefSharp.7z
이 버전이 현재 최신 버전 맞을까요? 이 버전으로 시도했는데 현재 라운드 인식이 안되는 것 같고 자동 입력도 안되는 것 같습니다.

**Comment by keamlfea** [comment]
직접 빌드 해서 테스트도 해봤는데 동일한 문제가 있네요
제 생각이 맞다면.. 끄투코리아 측에서 업데이트를 해서 패치한 것 같습니다
확인 해주시면 감사하겠습니다

**Comment by keamlfea** [comment]
[CefSharp.log](https://github.com/hsheric0210/AutoKkutu/files/12194890/CefSharp.log)

**Comment by hsheric0210** [comment]
일단 주된 문제인 '단어 추가/제거 시 크래시' 문제는 데이터베이스가 초기화되기 전, 너무 일찍 '데이터베이스 관리' 메뉴를 열었기에 발생되는 것으로 보여집니다.
관련된 데이터베이스 오류들(크래시 포함)은 58496ce7cb8cc141272f31fe185ed3746a2a74d7 에서 모두 수정되었습니다.

단어 입력 등이 되지 않는 버그의 경우, 로그를 보면 사이트 측에 주입되어야 할 스크립트가 제대로 주입되지 않아 발생한 문제로 보입니다.

혹시 **해당 입력 버그가 발상했을 당시의** *전체* 로그 파일을 올려주실 수 있으신가요?
프로그램 로그 파일의 이름은 'AutoKkutu.log'이며, 'AutoKkutu_\<N\>.log'으로 파일명 뒷쪽에 숫자가 붙어 있을 수도 있습니다.

**Comment by hsheric0210** [comment]
현재 자동 입력이 안 되는 문제는 아마도 기본 설정 파일 상 입력기가 존재하지 않는 입력기로 잡혀 있는 문제 때문으로 보입니다. ('Win32InputSimulator'(존재하지 않음) -> 'Win32InputSimulate')
해당 문제는 최신 버전에서 고쳐졌으며, 또는 설정 창에서 다른 입력기를 선택하고 다시 설정을 저장하는 식으로도 우회할 수 있습니다.

**Comment by keamlfea** [comment]
답변 감사드립니다.
1. 방금 최신 버전에서 테스트 해본 결과 최신 버전으로 업데이트 이후에는 어제 말씀드린 게임 라운드 인식이 안되거나 자동 입력이 안되는 문제는 없는 것으로 확인했습니다.
2. 데이터베이스에 단어 추가가 안되는 문제가 있는 것 같습니다. (수동 추가 / 라운드 끝난 후에 자동 추가 포함)
3. 입력 시뮬레이션(Win32)으로 설정 되어있는 상태에서 채팅을 쳤을 때 채팅 뛰어 쓰기가 안되는 문제가 있는 것 같습니다

[AutoKkutu.log](https://github.com/hsheric0210/AutoKkutu/files/12208137/AutoKkutu.log)
[CefSharp.log](https://github.com/hsheric0210/AutoKkutu/files/12208138/CefSharp.log)
첨부한 로그는 최신 버전에서 테스트한 로그입니다

**Comment by keamlfea** [comment]
그리고 현재 데이터베이스에 단어 추가가 안되는 문제가 있는 것 같습니다.. 이것도 로그 확인 해주시면 감사하겠습니다

**Comment by keamlfea** [comment]
[AutoKkutu.log](https://github.com/hsheric0210/AutoKkutu/files/12208134/AutoKkutu.log)
[CefSharp.log](https://github.com/hsheric0210/AutoKkutu/files/12208135/CefSharp.log)

**Comment by keamlfea** [comment]
어제 문제가 발생했던 버전(업데이트 전) 로그도 첨부하겠습니다.
최신 버전과 다르게 기존 버전은 게임 인식, 라운드 인식, 단어 자동 추가가 안되는 문제가 있습니다.

[AutoKkutu [기존 버전].log](https://github.com/hsheric0210/AutoKkutu/files/12208189/AutoKkutu.log)
[CefSharp [기존 버전].log](https://github.com/hsheric0210/AutoKkutu/files/12208190/CefSharp.log)

**Comment by hsheric0210** [comment]
넵 문제 원인을 확인하였습니다. 빠른 시일 내 수정하도록 하겠습니다.

* [x] 데이터베이스에 단어 추가가 안되는 문제 (SQL 오류)
```
07:00:49.5890 [ERR] <Thread#16> [DbUpdateJob] 단어 웡웡를 데이터베이스에 추가할 수 없습니다.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'table word_list has no column named type'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in /_/Dapper/SqlMapper.cs:line 2928
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 648
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 519
   at AutoKkutuLib.Database.Sql.Query.WordAdditionQuery.Execute() in C:\projects\autokkutu\AutoKkutuLib\Database\Sql\Query\WordAdditionQuery.cs:line 34
   at AutoKkutuLib.Database.Sql.Query.WordAdditionQuery.Execute(String word, WordFlags wordFlags) in C:\projects\autokkutu\AutoKkutuLib\Database\Sql\Query\WordAdditionQuery.cs:line 17
   at AutoKkutuLib.Database.Jobs.DbUpdateJob.AddNewPaths(ICollection`1 paths) in C:\projects\autokkutu\AutoKkutuLib\Database\Jobs\DbUpdateJob.cs:line 98
```

* [x] Win32InputSimulate 모드에서 띄어쓰기가 되지 않는 버그
```
07:00:43.4751 [WRN] <Thread#11> [Win32InputSimulator] Win32-InputSimulator: VkCode not found for character " "
```

**Comment by hsheric0210** [comment]
이전 버전에서 게임 상태가 제대로 감지되지 않는 문제는 아마도 사이트 프레임이 새로 로드될 때, 라이브러리 파사드 전체가 언로드되는 문제와 관련이 있어 보입니다.

```
2023-07-30 07:45:53.1676 [VRB] <Thread#10> [] Browser Page Load: www.facebook.com
2023-07-30 07:45:53.1676 [INF] <Thread#10> [] Disposed previous facade.              <------
2023-07-30 07:45:53.1676 [WRN] <Thread#10> [] 지원되지 않는 사이트: www.facebook.com
```

* [x] 새로 로드된 사이트가 지원되지 않는 사이트인 경우, 라이브러리 파사드 정리하지 않기.

**Comment by hsheric0210** [comment]
위 3가지 문제 현상 모두 8ddf7e715266cd243f44b1ab467adcd156eff0a4 에서 수정되었습니다.

위 단어 추가 시 SQL 오류가 발생하는 문제는 일부 데이터베이스 마이그레이션들이 제대로 적용되지 않아 발생하는 문제로,
모든 데이터베이스 마이그레이션들이 정상적으로 작동하는 최신 버전에서 한 번만 프로그램을 켰다 꺼 주어도 해결됩니다. (프로그램 시작 시 데이터베이스 로드 단계에서 마이그레이션 적용)
