### ISSUE TITLE
'StoredProcedure' is not supported. 오류 발생

### ISSUE THREAD

**Issue by dog898996** [hsheric0210/AutoKkutu#92]
데이터베이스 검증을 시도하면 콘솔에 아래와 같이 출력되며 오류가 발생합니다.

2024-01-12 00:31:50.1058 [INF] <Thread#54> [DbCheckJob] Database has Total 16488 elements.
2024-01-12 00:31:50.1058 [INF] <Thread#54> [DbCheckJob] Deduplicating entries...
2024-01-12 00:31:50.1156 [INF] <Thread#54> [DbCheckJob] Removed 0 duplicate entries. Took 9ms.
2024-01-12 00:31:50.1156 [INF] <Thread#54> [DbCheckJob] Updating node lists...
2024-01-12 00:31:50.1160 [INF] <Thread#54> [DbCheckJob] Done refreshing node lists. Took 0ms.
2024-01-12 00:31:50.1160 [INF] <Thread#54> [DbCheckJob] Searching problems...
2024-01-12 00:31:50.1970 [INF] <Thread#54> [DbCheckJob] Done searching problems. Took 81ms.
2024-01-12 00:31:50.1972 [INF] <Thread#54> [DbCheckJob] Done fixing problems. Took 0ms.
2024-01-12 00:31:50.1972 [INF] <Thread#54> [DbCheckJob] Executing vacuum...
2024-01-12 00:31:50.1973 [ERR] <Thread#54> [DbCheckJob] Exception while checking database
System.ArgumentException: The CommandType 'StoredProcedure' is not supported.
   at Microsoft.Data.Sqlite.SqliteCommand.set_CommandType(CommandType value)
   at Dapper.CommandDefinition.SetupCommand(IDbConnection cnn, Action`2 paramReader) in /_/Dapper/CommandDefinition.cs:line 129
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in /_/Dapper/SqlMapper.cs:line 2970
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 656
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 527
   at AutoKkutuLib.Database.Sql.Query.VacuumQuery.Execute() in C:\projects\autokkutu\AutoKkutuLib\Database\Sql\Query\VacuumQuery.cs:line 13
   at AutoKkutuLib.Database.Jobs.DbCheckJob.ExecuteVacuum() in C:\projects\autokkutu\AutoKkutuLib\Database\Jobs\DbCheckJob.cs:line 253
   at AutoKkutuLib.Database.Jobs.DbCheckJob.<>c__DisplayClass4_0.<CheckDB>b__0() in C:\projects\autokkutu\AutoKkutuLib\Database\Jobs\DbCheckJob.cs:line 114

**Comment by hsheric0210** [comment]
혹시 최신 커밋 빌드로 다시 시도해보실 수 있나요?
보아하니 ad1146156ab502369411e4dee05d9175f9e389bf 에서 이미 해결된 문제인 것 같아서...

최신 빌드는 [여기](https://ci.appveyor.com/project/hsheric0210/autokkutu)에서 다운로드할 수 있어요.

**Comment by dog898996** [comment]
아하... 넵

**Comment by scottjsh** [comment]
만료되어 받을 수 없네요
