### ISSUE TITLE
실행하자마자 오류가 납니다.

### ISSUE THREAD

**Issue by ConstaX-only** [hsheric0210/AutoKkutu#93]
2024-02-10 19:09:10.9540 [INF] <Thread#1> [] Start loading page...
2024-02-10 19:09:11.0253 [VRB] <Thread#1> [] Initializing browser
2024-02-10 19:09:11.0521 [ERR] <Thread#1> [] Initialization failure
System.IO.FileNotFoundException: Could not load file or assembly 'CefSharp.Core.Runtime, Version=119.1.20.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138'. The system cannot find the file specified.
File name: 'CefSharp.Core.Runtime, Version=119.1.20.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138'
   at CefSharp.CefSettingsBase..ctor()
   at CefSharp.Wpf.CefSettings..ctor() in C:\projects\cefsharp\CefSharp.Wpf\CefSettings.cs:line 16
   at AutoKkutuLib.CefSharp.CefSharpBrowser.CefConfigToCefSettings(CefConfigDto config) in C:\projects\autokkutu\AutoKkutuLib.CefSharp\CefSharpBrowser.cs:line 37
   at AutoKkutuLib.CefSharp.CefSharpBrowser..ctor() in C:\projects\autokkutu\AutoKkutuLib.CefSharp\CefSharpBrowser.cs:line 107
   at AutoKkutuGui.Main.InitializeBrowser() in C:\projects\autokkutu\AutoKkutuGui\Main.Initialize.cs:line 55
   at AutoKkutuGui.Main.NewInstance() in C:\projects\autokkutu\AutoKkutuGui\Main.Initialize.cs:line 25
2024-02-10 19:09:11.0577 [FTL] <Thread#1> [] Program crashed! Report this to the developer.
System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'AutoKkutuGui.MainWindow' that matches the specified binding constraints threw an exception.
 ---> System.AggregateException: AutoKkutu instance initialization failure (Could not load file or assembly 'CefSharp.Core.Runtime, Version=119.1.20.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138'. The system cannot find the file specified.)
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'CefSharp.Core.Runtime, Version=119.1.20.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138'. The system cannot find the file specified.
File name: 'CefSharp.Core.Runtime, Version=119.1.20.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138'
   at CefSharp.CefSettingsBase..ctor()
   at CefSharp.Wpf.CefSettings..ctor() in C:\projects\cefsharp\CefSharp.Wpf\CefSettings.cs:line 16
   at AutoKkutuLib.CefSharp.CefSharpBrowser.CefConfigToCefSettings(CefConfigDto config) in C:\projects\autokkutu\AutoKkutuLib.CefSharp\CefSharpBrowser.cs:line 37
   at AutoKkutuLib.CefSharp.CefSharpBrowser..ctor() in C:\projects\autokkutu\AutoKkutuLib.CefSharp\CefSharpBrowser.cs:line 107
   at AutoKkutuGui.Main.InitializeBrowser() in C:\projects\autokkutu\AutoKkutuGui\Main.Initialize.cs:line 55
   at AutoKkutuGui.Main.NewInstance() in C:\projects\autokkutu\AutoKkutuGui\Main.Initialize.cs:line 25
   --- End of inner exception stack trace ---
   at AutoKkutuGui.Main.NewInstance() in C:\projects\autokkutu\AutoKkutuGui\Main.Initialize.cs:line 40
   at AutoKkutuGui.Main.GetInstance() in C:\projects\autokkutu\AutoKkutuGui\Main.cs:line 63
   at AutoKkutuGui.MainWindow..ctor() in C:\projects\autokkutu\AutoKkutuGui\MainWindow.xaml.cs:line 51
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at AutoKkutuGui.App.Main()

무엇이 문제일까요? 운영 체제는 윈도우10을 사용하고, Intel 10세대 CPU를 사용하고 있습니다.

**Comment by BING87238** [comment]
<img width="970" alt="2024-04-04_175938" src="https://github.com/hsheric0210/AutoKkutu/assets/132109721/7176b9a7-f0d5-43af-93fc-2b9d622f3e20">
